#include "instructions.h"

void opcode_NOP() {
  // No Operation - Waste some cycles
}

// Placeholder, should do the same as a NOP
void opcode_UNDEF() { opcode_NOP(); }

Opcode instruction_set[256] = {
  { "NOP",       .length=1, .cycles=4,  &opcode_NOP },
  { "LXI B,d16", .length=3, .cycles=10, &opcode_UNDEF },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  { "CMP E",    .length=1, .cycles= 4, &opcode_UNDEF },
  { "CMP H",    .length=1, .cycles= 4, &opcode_UNDEF },
  { "CMP L",    .length=1, .cycles= 4, &opcode_UNDEF },
  { "CMP M",    .length=1, .cycles= 7, &opcode_UNDEF },
  { "CMP A",    .length=1, .cycles= 4, &opcode_UNDEF },
  { "RNZ",      .length=1, .cycles= 5, &opcode_UNDEF },
  { "POP B",    .length=1, .cycles=10, &opcode_UNDEF },
  { "JNZ a16",  .length=3, .cycles=10, &opcode_UNDEF },
  { "JMP a16",  .length=3, .cycles=10, &opcode_UNDEF },
  { "CNZ a16",  .length=3, .cycles=11, &opcode_UNDEF },
  { "PUSH B",   .length=1, .cycles=11, &opcode_UNDEF },
  { "ADI d8",   .length=2, .cycles= 7, &opcode_UNDEF },
  { "RST 0",    .length=1, .cycles=11, &opcode_UNDEF },
  { "RZ",       .length=1, .cycles= 5, &opcode_UNDEF },
  { "RET",      .length=1, .cycles=10, &opcode_UNDEF },
  { "JZ a16",   .length=3, .cycles=10, &opcode_UNDEF },
  { "*JMP a16", .length=3, .cycles=10, &opcode_UNDEF },
  { "CZ a16",   .length=3, .cycles=11, &opcode_UNDEF },
  { "CALL a16", .length=3, .cycles=17, &opcode_UNDEF },
  { "ACI d8",   .length=2, .cycles= 7, &opcode_UNDEF },
  { "RST 1",    .length=1, .cycles=11, &opcode_UNDEF },
  { "RNC",      .length=1, .cycles= 5, &opcode_UNDEF },
  { "POP D",    .length=1, .cycles=10, &opcode_UNDEF },
  { "JNC a16",  .length=3, .cycles=10, &opcode_UNDEF },
  { "OUT d8",   .length=2, .cycles=10, &opcode_UNDEF },
  { "CNC a16",  .length=3, .cycles=11, &opcode_UNDEF },
  { "PUSH D",   .length=1, .cycles=11, &opcode_UNDEF },
  { "SUI d8",   .length=2, .cycles= 7, &opcode_UNDEF },
  { "RST 2",    .length=1, .cycles=11, &opcode_UNDEF },
  { "RC",       .length=1, .cycles= 5, &opcode_UNDEF },
  { "*RET",     .length=1, .cycles=10, &opcode_UNDEF },
  { "JC a16",   .length=3, .cycles=10, &opcode_UNDEF },
  { "IN d8",    .length=2, .cycles=10, &opcode_UNDEF },
  { "CC a16",   .length=3, .cycles=11, &opcode_UNDEF },
  { "*CALL a16",.length=3, .cycles=17, &opcode_UNDEF },
  { "SBI d8",   .length=2, .cycles= 7, &opcode_UNDEF },
  { "RST 3",    .length=1, .cycles=11, &opcode_UNDEF },
  { "RPO",      .length=1, .cycles= 5, &opcode_UNDEF },
  { "POP H",    .length=1, .cycles=10, &opcode_UNDEF },
  { "JPO a16",  .length=3, .cycles=10, &opcode_UNDEF },
  { "XTHL",     .length=1, .cycles=18, &opcode_UNDEF },
  { "CPO a16",  .length=3, .cycles=11, &opcode_UNDEF },
  { "PUSH H",   .length=1, .cycles=11, &opcode_UNDEF },
  { "ANI d8",   .length=2, .cycles= 7, &opcode_UNDEF },
  { "RST 4",    .length=1, .cycles=11, &opcode_UNDEF },
  { "RPE",      .length=1, .cycles= 5, &opcode_UNDEF },
  { "PCHL",     .length=1, .cycles= 5, &opcode_UNDEF },
  { "JPE a16",  .length=3, .cycles=10, &opcode_UNDEF },
  { "XCHG",     .length=1, .cycles= 5, &opcode_UNDEF },
  { "CPE a16",  .length=3, .cycles=11, &opcode_UNDEF },
  { "*CALL a16",.length=3, .cycles=17, &opcode_UNDEF },
  { "XRI d8",   .length=2, .cycles= 7, &opcode_UNDEF },
  { "RST 5",    .length=1, .cycles=11, &opcode_UNDEF },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  },
  {  }
};
